README: While MaraDNS will compile, it won’t run w/o /dev/urandom
Exception: The Windows port uses Windows specific calls to get entropy
(Actually, the Windows port of MaraDNS gets entropy from secret.txt, and
another program needs to generate that file, but the Windows port of
Deadwood gets entropy via Windows API specific calls)